name: Ender VNC

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Downloading & Setting Up
        run: |
         echo Running!
         Invoke-WebRequest -Uri "" -OutFile "runvnc.bat"
         cmd /c runvnc.bat

      - name: Time Counter
        run: python time.py
